batch_size: 128
n_workers: 4
optimizer:
  lr: 1.0e-4
scheduler:
  gamma: [1, 0.1]
  milestones: [500, 800]
n_epoches: 900
train_stat_interval: 1000
val_stat_interval: 20000
check_cluster_interval: 1000
